server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    root /home/ubuntu/pixel-life/www;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    }
}
